---
functional:
  - Пользователь должен иметь возможность зарегистрироваться с помощью электронной почты
  - Пользователь должен получить письмо-подтверждение о регистрации на электронную почту
  - Пользователь должен иметь возможность авторизоваться на сайте с помощью электронной почты, Github, Discord
  - Пользователь должен иметь возможность восстановить пароль с помощью электронной почты
  - Пользователь должен иметь возможность создавать игру с ботом
  - Пользователь должен иметь возможность подключаться к созданной игре в качестве зрителя
  - Пользователь должен иметь возможность отправить приглашение на участие в игре
  - Пользователь должен иметь возможность создавать игру открытую для всех пользователей
  - Пользователь должен иметь возможность присоединяться к созданной игре в качестве участника
  - Пользователь должен иметь возможность при создании игры присвоить игре 4-ре уровня сложности - elemenatry, easy, medium, hard
  - Пользователь должен иметь возможность создавать игру из предложенного списка игр или выбирать игру по тегам
  - Пользователь должен иметь возможность создавать турнир
  - Пользователь должен иметь возможность создать игру без регистрации
  - Пользователь должен иметь возможность просматривать свою статистику игр
  - Пользователь должен иметь возможность сдаться в процессе игры
  - Пользователь должен иметь возможность отправить личное сообщение другому пользователю
  - Пользователь должен иметь возможность измненения языка программирования в качестве оружия для сражения
  - Пользователь должен иметь возможность запустить матч-реванш по завершению игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть кроссплатформенным - адаптивная вёрстка для ПК и мобильных устройств
  - Сайт должен быть совместим с последними версиями браузеров - Google Chrome, Safari, Firefox, Opera, Яндекс. Браузер, Microsoft Edge
  - Сайт должен быть способен выдерживать 500 запросов в секунду
implicit:
 - Пользователь видит анимацию (графику) при победе, проигрыше
 - Пользователь слышит джинглы (звуковые эффекты) при победе, проигрыше
 - Пользователь должен иметь возможность выбора звуковых тем в личном кабинете
 - Пользователь должен иметь возможность менять никнейм
 - Nickname должен содержать латинские буквы, цифры (обязательно) и символы подчеркивания (необязательно).
 - Nickname пользователя не может начинаться с цифры
 - Nickname пользователя должен быть от 3 до 16 символов
 - Email пользователя должен содержать @
